# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx-email-validator:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx-email-validator
    # проброс портов
    ports:
      - "80:80"
    volumes:
      - ./code:/data/email-verification.local
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  fpm-email-validator:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: fpm-email-validator # имя контейнера после запуска
    volumes:
      - ./code:/data/email-verification.local
      - ./fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-network

  cli-email-validator:
    build:
      context: .
      dockerfile: ./cli/Dockerfile
    container_name: cli-email-validator
    volumes:
      - ./code:/app
    tty: true
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge