stages:
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export DIR=$(date +%Y%m%d_%H%M%S)

deploy_server1:
  stage: deploy
  environment:
    name: server1
    url: $SERVER1
  script:
    - ssh $SSH_USER@$SERVER1 "cd /data/application.local &&
      git clone https://olelishna-deploy:i6LUaV2Dg8TQhQzLbVh8@gitlab.com/olelishna/credit-request.git $DIR &&
      sudo chown www-data:www-data $DIR -R &&
      cd $DIR &&
      sh ./deploy.sh $SERVER1 $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD $MEMCACHED_HOST $MEMCACHED_PORT &&
      cd .. &&
      ( [ ! -d /data/application.local/current ] || mv -Tf /data/application.local/current /data/application.local/previous ) &&
      ln -s /data/application.local/$DIR /data/application.local/current"
  only:
    - master
