# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 8.1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
    branch: main

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

# Commands to be run before your environment runs.
before_script:
  - cp .env.example .env
  - cd code
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cd ../

script:
  - docker-compose down
  - docker-compose build
  - docker-compose up -d

# Customize when the notification emails are sent.
notifications:
  email: true
  on_success: never
  on_failure: always

