# build here: https://app.travis-ci.com/github/nujensait/otus_hw16_queues/builds/260119105
# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 8.1

# deployment settings
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
    branch: main

sudo: required
services:
  - docker

# enviroment variables
env:
  COMPOSE_VERSION: 1.4.1

# steps before install
before_install:
  - cp code/src/Application/Views/info.php code/src/Application/Views/tmp.php
  - mv code/src/Application/Views/deploy.php code/src/Application/Views/info.php
  - echo "begin deploy"

# Commands to be run before your environment runs.
before_script:
  - cp .env.example .env
  - cd code
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cd ../

# deployment scripts
script:
  - docker-compose down
  - docker-compose build
  - docker-compose up -d

# after setup
after_install:
  - cp code/src/Application/Views/tmp.php code/src/Application/Views/info.php

# Customize when the notification emails are sent.
notifications:
  email: true
  on_success: never
  on_failure: always

