#!/bin/bash

total=0
maxCountNum=2
if [[ $# -ne $maxCountNum ]]; then
    echo "Max number of parameters $maxCountNum"
    exit 1
fi
for var in "$@"; do
    if ! [[ $var =~ ^[\-0-9]+$ ]] ; then
      echo "error: $var Not a number"; exit 1
    fi
	  total=$(($total + $var))
done

echo "Total is $total"
echo $countNum