#!/bin/bash

total=0
maxCountNum=2
if [[ $# -ge $maxCountNum+1 ]]; then
    echo "Max number of parameters $maxCountNum"
    exit 1
fi

REGEX_IS_NUMBER='^[-]?[0-9]+([.]{1}[0-9]+)?$'
for var in "$@"; do
    if ! [[ $var =~ $REGEX_IS_NUMBER ]] ; then
      echo "error: $var Not a number"; exit 1
    fi
	  total="$total+$var"
done

total=$(awk "BEGIN {print ($total)}")
echo "Total is $total"