CREATE TABLE "films" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "description" text,
                         "duration" int,
                         "price" float
);
CREATE TABLE "halls" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "seats" int
);
CREATE TABLE "halls_films" (
                               "film_id" int,
                               "hall_id" int
);
CREATE TABLE "orders" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "client_id" int,
                          "film_id" int,
                          "price" float,
                          "hall_id" int,
                          "seat" int,
                          "session_id" int,
                          "date" date
);
CREATE TABLE "seats" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "place" int,
                         "hall_id" int,
                         "session_id" int,
                         "is_free" boolean
);
CREATE TABLE "client" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar,
                          "email" varchar
);
CREATE TABLE "sessions" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "time_start" timestamp,
                            "time_finish" timestamp,
                            "coefficient" float
);

ALTER TABLE "halls_films" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");
ALTER TABLE "halls_films" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("seat") REFERENCES "seats" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("id");
ALTER TABLE "seats" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("id");
ALTER TABLE "seats" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("id");

INSERT INTO halls (name, seats)
VALUES ('Зал 1', 77);
INSERT INTO halls (name, seats)
VALUES ('Зал 2', 77);
INSERT INTO halls (name, seats)
VALUES ('Зал 3', 78);
INSERT INTO halls (name, seats)
VALUES ('Зал 4', 79);
INSERT INTO halls (name, seats)
VALUES ('Зал 5', 70);

INSERT INTO sessions (time_start, time_finish, coefficient)
VALUES ('2022-11-23 00:07:30.000000', '2022-11-23 00:09:30.000000', '1.75');
INSERT INTO sessions (time_start, time_finish, coefficient)
VALUES ('2022-11-29 00:07:30.000000', '2022-11-29 00:09:30.000000', '1.50');
INSERT INTO sessions (time_start, time_finish, coefficient)
VALUES ('2022-11-28 00:07:30.000000', '2022-11-28 00:09:30.000000', '1.1');
INSERT INTO sessions (time_start, time_finish, coefficient)
VALUES ('2022-11-25 00:07:30.000000', '2022-11-25 00:09:30.000000', '1.75');


INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (1, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (2, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (3, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (4, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (5, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (6, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (7, 2, 1, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (1, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (2, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (3, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (4, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (5, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (6, 1, 3, false);
INSERT INTO seats (place, hall_id, session_id, is_free)
VALUES (7, 1, 3, false);

INSERT INTO films (name, description, duration, price)
VALUES ('Любовь и голуби', 'Фильм о любви', 122, 500);
INSERT INTO films (name, description, duration, price)
VALUES ('Бриллиантовая рука', 'Комедия', 180, 600);
INSERT INTO films (name, description, duration, price)
VALUES ('Собачье сердце', 'Драма', 100, 500);

INSERT INTO client (name, email)
VALUES ('Jason Smith', 'ex@gmail.com');
INSERT INTO client (name, email)
VALUES ('Lee Bruce', 'lee@gmail.com');
INSERT INTO client (name, email)
VALUES ('Jaky Chan', 'jacky@gmail.com');
INSERT INTO client (name, email)
VALUES ('Brad Pitt', 'brad@gmail.com');


INSERT INTO halls_films (film_id, hall_id)
VALUES (1, 1);
INSERT INTO halls_films (film_id, hall_id)
VALUES (2, 1);
INSERT INTO halls_films (film_id, hall_id)
VALUES (3, 1);
INSERT INTO halls_films (film_id, hall_id)
VALUES (1, 2);
INSERT INTO halls_films (film_id, hall_id)
VALUES (2, 2);

INSERT INTO orders (client_id, film_id, price, hall_id, seat, session_id, "date")
VALUES (1, 1, 900, 3, 12, 1, '2022-11-23 00:07:30.000000');
INSERT INTO orders (client_id, film_id, price, hall_id, seat, session_id, "date")
VALUES (1, 1, 900, 3, 13, 1, '2022-11-23 00:07:30.000000');
INSERT INTO orders (client_id, film_id, price, hall_id, seat, session_id, "date")
VALUES (1, 3, 900, 3, 7, 1, '2022-11-23 00:07:30.000000');
INSERT INTO orders (client_id, film_id, price, hall_id, seat, session_id, "date")
VALUES (1, 2, 900, 3, 3, 1, '2022-11-23 00:07:30.000000');
