services:
  php-fpm:
    build:
      context: docker/php-fpm
    container_name: amarkhay_php-fpm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      PHP_IDE_CONFIG: 'serverName=server'
    networks:
      - app-network

  nginx:
    build:
      context: docker/nginx
    container_name: amarkhay_nginx
    volumes:
      - .:/var/www/app
#    ports:
#      - "80:80"
#      - "443:443"
    networks:
      - app-network