version: '3'

services:
  balanser:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: balance/nginx-balanser
    container_name: nginx-balacer
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/balanser.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  nginx1:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: balance/nginx
    container_name: nginx1
    volumes:
       - ./code:/data/mysite.local
       - ./nginx/hosts/app1.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  app1:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: balance/php # имя будущего образа
    container_name: app1 # имя контейнера после запуска
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx-app2
    container_name: nginx2
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/app2.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: balance/php # имя будущего образа
    container_name: app2 # имя контейнера после запуска
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  nginx3:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx-app3
    container_name: nginx3
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/app3.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  app3:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: balance/php # имя будущего образа
    container_name: app3 # имя контейнера после запуска
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  workspace:
    build:
      context: .
      dockerfile: php/ConsoleDockerfile
    image: balance/workspace
    container_name: workspace
    volumes:
      - ./code:/var/www
    networks:
      - app-network

  memcached:
    container_name: memcached
    image: memcached:latest
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge