version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    container_name: app-nginx
    working_dir: /var/www
    volumes:
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

  php-fpm:
    build:
      context: docker/images/php-fpm
    container_name: app-php-fpm
    volumes:
      - ./src:/var/www/app.local
    working_dir: /var/www/
    restart: always
    networks:
      - app-network

  postgresql:
    image: postgres:14.5-alpine
    container_name: app-postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7.0.5-alpine
    container_name: app-redis
    restart: always
    ports:
      - "6380:6380"
    networks:
      - app-network
    
  memcached:
    image: memcached:1.6.17-alpine
    container_name: app-memcached
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
