version: "3.2"

services:
  nginx:
    image: nginx:alpine
    container_name: homework-nginx
    ports:
      - "8088:80"
    volumes:
      - ./code:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: homework/18/fpm
    container_name: homework-app
    volumes:
      - ./code:/var/www
      - .env:/var/www/.env
    networks:
      - app-network

  workspace:
    build:
      context: .
      dockerfile: docker/php/ConsoleDockerfile
    image: homework/18/workspace
    container_name: homework-workspace
    volumes:
      - ./code:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge