version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local/
    networks:
      - app-network

  app:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    image: php-fpm
    container_name: app
    volumes:
      - ./code:/data/mysite.local/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge