version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx_otus
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  app:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app_otus
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge