version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
       - ./code:/data/mysite.local
    depends_on:
      - fpm
      - elasticsearch
    networks:
      - app-network

  fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: app/fpm
    container_name: fpm
    volumes:
       - ./code:/data/mysite.local
    environment:
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      ES_PORT: ${ES_PORT}
    depends_on:
      - elasticsearch
    networks:
      - app-network

  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic_search
    ports:
      - "9200:${ES_PORT}"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elastic-search-data:/usr/share/elasticsearch/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
