version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
       - ./code:/data/application.local
       - ./sock:/sock
       - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
       - ./code:/data/application.local
       - ./sock:/sock
       - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./dbdata/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
        - "11211:11211"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
