version: '3'

services:
  socket-server:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: balance/php
    container_name: socket-server
    working_dir: /data/mysite.local
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  socket-client:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: balance/php
    container_name: socket-client
    working_dir: /data/mysite.local
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  workspace:
    build:
      context: .
      dockerfile: php/ConsoleDockerfile
    image: balance/workspace
    container_name: workspace
    working_dir: /data/mysite.local
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge