version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: homework-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: homework/15/fpm
    container_name: homework-app
    restart: unless-stopped
    volumes:
      - ./code:/var/www
      - .env:/var/www/.env
    networks:
      - app-network

  workspace:
    build:
      context: .
      dockerfile: docker/php/ConsoleDockerfile
    image: homework/15/workspace
    container_name: homework-workspace
    restart: unless-stopped
    volumes:
      - ./code:/var/www
    networks:
      - app-network

  database:
    image: postgres:11.2-alpine
    container_name: homework-postgres
    volumes:
      - ./.dev/postgres:/var/lib/postgresql/data
      - ./docker/postgres/dump:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54322:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge