version: '3'

services:
  #контейнер с Nginx (only upstream)
  nginx1:
    build:
      context: ./nginx
      dockerfile: nginx/Dockerfile
    image: balance/nginx
    container_name: nginx_upstream_hw3
     #проброс портов
    ports:
     - "80:80"
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/nginx1_upstream.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  #контейнер с Nginx2
  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx2_hw3
     #проброс портов
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/nginx2_app1.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  #контейнер с Nginx3
  nginx3:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx3_hw3
     #проброс портов
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/nginx3_app2.conf:/etc/nginx/conf.d/mysite.local.conf
    networks:
      - app-network

  #Контейнер с PHP-FPM #1
  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php # имя будущего образа
    container_name: app1_hw3 # имя контейнера после запуска
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  #Контейнер с PHP-FPM #2
  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app2_hw3
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network
  
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/dbdata:/var/lib/mysql  
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge