version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
       - ./code:/data/mysite.local
       - ./tmp/log/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - app-network

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: app/fpm
    container_name: fpm
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
