version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: homework-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - local

  app:
    build:
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    image: homework12/app
    container_name: homework-app
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - nginx
    networks:
      - local

  workspace:
    build:
      context: .
      dockerfile: ./docker-compose/php/ConsoleDockerfile
    image: homework12/workspace
    container_name: homework-workspace
    volumes:
      - ./:/var/www
    networks:
      - local

  postgres:
    image: postgres:11.2-alpine
    container_name: homework-db
    restart: always
    volumes:
      - ./.dev/postgres:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - local

  elasticsearch:
    image: elasticsearch:8.1.0
    container_name: homework-el
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./.dev/elastic:/usr/share/elasticsearch/data
    networks:
      - local

  kibana:
    image: kibana:8.1.0
    container_name: homework-kb
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - local
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  redis:
    image: redis:6.0
    container_name: homework-redis
    restart: always
    networks:
      - local

networks:
  local:
    driver: bridge
