version: '3'

services:
  app-server:
    build:
      context: ./Docker/fpm
      dockerfile: Dockerfile
    image: chat/php-server
    container_name: app-server
    volumes:
       - .:/chat-app
       - ./sock:/sock
    networks:
      - app-network

  app-client:
    build:
      context: ./Docker/fpm
      dockerfile: Dockerfile
    image: chat/php-client
    container_name: app-client
    volumes:
       - .:/chat-app
       - ./sock:/sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
