version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
       - ./code:/data/mysite.local
       - ./tmp/log/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - app-network

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: app/fpm
    container_name: fpm
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./tmp/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
