version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver_otus
    ports:
      - "80:80"
    volumes:
      - ./code:/data/application.local
    networks:
      - app-network

  app:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app_otus
    volumes:
      - ./code:/data/application.local
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_otus
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge