version: '3.8'

services:
  nginx:
    build:
      context: docker/nginx
      args:
        - WORKDIR=${DOCKER_WORKDIR}
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./${DOCKER_APPDIR}:${DOCKER_WORKDIR}
      - ./${DOCKER_DIR}/data/nginx/logs:/var/log/nginx
    networks:
      - app-network
  php-fpm:
    build:
      context: docker/php-fpm
      args:
        - WORKDIR=${DOCKER_WORKDIR}
        - PHP_VERSION=${DOCKER_PHP_VERSION}
    volumes:
      - ./${DOCKER_APPDIR}:${DOCKER_WORKDIR}
    networks:
      - app-network
  redis:
    build:
      context: docker/redis
    volumes:
      - ./${DOCKER_DIR}/data/redis:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge