version: '3'

services:
  nginx:
    build:
      context: ./nginx
    image: myapp/nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  app:
    build:
      context: ./fpm
    image: myapp/php
    container_name: app
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./dbdata/redis:/var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

networks:
  app-network:
    driver: bridge
