version: '3'

services:
  app1:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app1
    volumes:
      - .:/data/hw6
    networks:
      - app-socket

networks:
  app-socket:
    driver: bridge

