version: '3'

services:
    nginx-balancer:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx-balancer
        ports:
            - "81:80"
        volumes:
            - ./nginx/hosts/nginx_balancer.conf:/etc/nginx/conf.d/application.local.conf
        networks:
            - app-network

    nginx1:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx1
        ports:
            - "82:80"
        volumes:
            - ./public:/data/application.local
            - ./nginx/hosts/application1.local.conf:/etc/nginx/conf.d/application.local.conf
        networks:
            - app-network

    nginx2:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx2
        ports:
            - "83:80"
        volumes:
            - ./public:/data/application.local
            - ./nginx/hosts/application2.local.conf:/etc/nginx/conf.d/application.local.conf
        networks:
            - app-network

    nginx3:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx3
        ports:
            - "84:80"
        volumes:
            - ./public:/data/application.local
            - ./nginx/hosts/application3.local.conf:/etc/nginx/conf.d/application.local.conf
        networks:
            - app-network

    app1:
        build:
            context: ./fpm
            dockerfile: Dockerfile
        image: php-fpm
        container_name: app1
        volumes:
            - ./public:/data/application.local
        networks:
            - app-network

    app2:
        build:
            context: ./fpm
            dockerfile: Dockerfile
        image: php-fpm
        container_name: app2
        volumes:
            - ./public:/data/application.local
        networks:
            - app-network

    app3:
        build:
            context: ./fpm
            dockerfile: Dockerfile
        image: php-fpm
        container_name: app3
        volumes:
            - ./public:/data/application.local
        networks:
            - app-network

    memcached:
        image: memcached:latest
        container_name: memcached
        ports:
            - "11211:11211"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge