# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    # проброс портов
    ports:
      - "80:80"
    volumes:
       - ./:/var/www
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  app1:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    container_name: app1 # имя контейнера после запуска
    volumes:
       - ./:/var/www
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  postgres:
    build: docker/postgres
    container_name: postgresql
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/config/localhost.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

#Docker Networks
networks:
  app-network:
    driver: bridge