version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
       - ./code:/data/application.local
       - ./sock:/sock
       - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
       - ./code:/data/application.local
       - ./sock:/sock
       - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
