version: "3"

services:

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx/hosts
    ports:
      - ${NGINX_PORT}
    volumes:
      - ./docker/nginx/balance/nginx.balance.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/mysite.local
    networks:
      - my-net

  nginx1:
    container_name: nginx1
    image: nginx:stable
    ports:
      - ${NGINX_PORT1}
    volumes:
      - ./docker/nginx/nginx1/mysite.local.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/mysite.local
    networks:
      - my-net

  app1:
    container_name: app1
    build: ./docker/fpm/app1
    links:
      - memcached:memcached3
    volumes:
      - .:/var/www/mysite.local
      - ./docker/fpm/app1/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - my-net

  nginx2:
    container_name: nginx2
    image: nginx:stable
    ports:
      - ${NGINX_PORT2}
    volumes:
      - ./docker/nginx/nginx2/mysite.local.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/mysite.local
    networks:
      - my-net

  app2:
    container_name: app2
    build: ./docker/fpm/app2
    links:
      - memcached2:memcached2
    volumes:
      - .:/var/www/mysite.local
      - ./docker/fpm/app2/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - my-net

  nginx3:
    container_name: nginx3
    image: nginx:stable
    ports:
      - ${NGINX_PORT3}
    volumes:
      - ./docker/nginx/nginx3/mysite.local.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/mysite.local
    networks:
      - my-net

  app3:
    container_name: app3
    build: ./docker/fpm/app3
    links:
      - memcached3:memcached3
    volumes:
      - .:/var/www/mysite.local
      - ./docker/fpm/app3/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - my-net

  db:
    container_name: mysql
    build:
      context: ./docker/mysql
      args:
        - TZ=${TZ}
        - TEMP_DIR=${TEMP_DIR}
        - DB_PORT=${DB_PORT}
        - DB_CHARSET=${DB_CHARSET}
        - DB_COLLASION=${DB_COLLASION}
        - DB_NAME=${DB_NAME}
    restart: always
    command: --init-file /usr/local/etc/mysql/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}
    volumes:
      - ./dbdata:/var/lib/mysql
      - .:/var/www/mysite.local
    networks:
      - my-net

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    restart: unless-stopped
    networks:
      - my-net


  memcached2:
    container_name: memcached2
    image: memcached:latest
    ports:
      - "11212:11211"
    restart: unless-stopped
    networks:
      - my-net


  memcached3:
    container_name: memcached3
    image: memcached:latest
    ports:
      - "11213:11211"
    restart: unless-stopped
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
