version: '3'

services:
  #Контейнер с PHP-FPM
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: fast-food
    volumes:
      - ./code:/data

