version: '3'

services:
  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./docker/dbdata/postgres:/var/lib/postgres