version: '3'

services:

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./code:/data/application.local
      - ./socket:/socket
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./code:/data/application.local
      - ./nginx/hosts/application.local.conf:/etc/nginx/conf.d/application.local.conf
      - ./socket:/socket
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/backups:/var/lib/backups
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network

  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge