# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:

  php_chat_client:
    depends_on:
      - php_chat_server
    build:
      context: docker-config/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: php_chat_client
    hostname: php_chat_client
    volumes:
      - ./src:/www/application.local/src
      - ./vendor:/www/application.local/vendor
      - ./config:/etc/chat
      - ./tmp:/tmp
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  php_chat_server:
    build:
      context: docker-config/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: php_chat_server
    hostname: php_chat_server
    volumes:
       - ./src:/www/application.local/src
       - ./vendor:/www/application.local/vendor
       - ./config:/etc/chat
       - ./tmp:/tmp
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

networks:
  app-network:
    driver: bridge