version: "3"

services:
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    image: balance/server
    volumes:
      - "./src:/src"
    ports:
      - "80:80"
    networks:
      - app-network

  fpm-1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: fpm-1
    image: balance/fpm
    volumes:
      - "./src:/src"
    networks:
      - app-network

  fpm-2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: fpm-2
    image: balance/fpm
    volumes:
      - "./src:/src"
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    command: -m 128
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge