version: '3'

services:
  nginx-b:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: hw4/nginx
    container_name: nginx-b
    ports:
      - "80:80"
    volumes:
      - ./code:/data/hw4.local
      - ./nginx/hosts/balance.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx1
    container_name: nginx1
    volumes:
      - ./code:/data/hw4.local
      - ./nginx/hosts/nginx1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx2
    container_name: nginx2
    volumes:
      - ./code:/data/hw4.local
      - ./nginx/hosts/nginx2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  nginx3:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx3
    container_name: nginx3
    volumes:
      - ./code:/data/hw4.local
      - ./nginx/hosts/nginx3.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: fpm
    container_name: app1
    volumes:
      - ./code:/data/hw4.local
    networks:
      - app-network

  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: fpm
    container_name: app2
    volumes:
      - ./code:/data/hw4.local
    networks:
      - app-network

  app3:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: fpm
    container_name: app3
    volumes:
      - ./code:/data/hw4.local
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    container_name: mysql
    networks:
      - app-network

networks:
   app-network:
     driver: bridge