version: "3"

services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: otus_web
    volumes:
      - .:/var/www/application
    networks:
      - app-network
  redis:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge