version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx_hw_11
    ports:
      - ${NGINX_PORT}:80
    volumes:
       - ./code:/data/mysite.local
       - ./tmp/log/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - app-network

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: app/fpm
    container_name: fpm_hw_11
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - MEMCACHED_PORT=${MEMCACHED_PORT}
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./tmp/redis:/data
    networks:
      - app-network

  memcached:
    image: memcached
    container_name: ${MEMCACHED_HOST}
    ports:
      - ${MEMCACHED_PORT}:11211
    volumes:
      - ./volumes/memcached:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
