version: "3"

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - .:/var/www/application
    ports:
      - ${APP_PORT}:80
    networks:
      - app-network
  php-fpm:
    build: ./docker/php-fpm
    container_name: otus_web
    volumes:
      - .:/var/www/application
    networks:
      - app-network
  database:
    image: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge