version: '3'

services:
  balancer:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    image: myapp/balancer
    container_name: balancer
    depends_on:
      - nginx1
      - nginx2
    ports:
      - "80:80"
    volumes:
      - ./code:/data/application.local
    networks:
      - app-network

  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx1
    depends_on:
      - app1
      - app2
    volumes:
       - ./code:/data/application.local
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx2
    depends_on:
      - app1
      - app2
    volumes:
      - ./code:/data/application.local
    networks:
      - app-network

  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app1
    volumes:
       - ./code:/data/application.local
    networks:
      - app-network

  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app2
    volumes:
      - ./code:/data/application.local
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: 'memcached'
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge