version: '3'

services:
  balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: balancer
    ports:
      - "80:80"
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network
      
  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network
      
  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app1
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app2
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '11211:11211'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge