version: '3.5'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx_hw_12
    ports:
      - ${NGINX_PORT}:80
    volumes:
       - ./code:/data/mysite.local
       - ./tmp/log/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - app-network

  fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: app/fpm
    container_name: fpm_hw_12
    volumes:
       - ./code:/data/mysite.local
       - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

  mysql:
    image: mysql
    container_name: db_mysql_hw_12
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
