# версия синтаксиса
version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/data/mysite.local
    networks:
      - app-network
  nginx1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx1
    volumes:
      - ./public:/data/mysite.local
    networks:
      - app-network

  nginx2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    container_name: nginx2
    volumes:
      - ./public:/data/mysite.local
    networks:
      - app-network
  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app1
    volumes:
      - ./public:/data/mysite.local
      - ./vendor:/data/vendor
      - ./src:/data/src
    networks:
      - app-network

  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app2
    volumes:
      - ./public:/data/mysite.local
      - ./vendor:/data/vendor
      - ./src:/data/src
    networks:
      - app-network

  app3:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app3
    volumes:
      - ./public:/data/mysite.local
      - ./vendor:/data/vendor
      - ./src:/data/src
    networks:
      - app-network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6378:6378'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local