version: '3'

services:
  #Контейнер с PHP-FPM
  server:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: chat/php
    container_name: server
    volumes:
      - ./code:/data
    networks:
      - app-network

  #Контейнер с PHP-FPM
  client:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: chat/php
    container_name: client
    volumes:
      - ./code:/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

