version: "3.9"
services:
  nginx:
    build:
      context: docker/nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local/
    networks:
      - app-network
    depends_on:
      - postgres

  php:
    build:
      context: docker/php
    image: php
    container_name: php
    volumes:
      - ./code:/data/mysite.local/
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata/pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge