# версия синтаксиса
version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
       - ./public:/data/mysite.local
    networks:
      - app-network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6378:6378'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
       - ./public:/data/mysite.local
       - ./vendor:/data/vendor
       - ./src:/data/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local