version: '3'

services:  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  # elasticsearch:
  #   image: elasticsearch:8.2.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   volumes:
  #     - ./data:/usr/share/elasticsearch/data
  #   networks:
  #     - app-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge