# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:

  database:
    image: mysql:latest
    environment:
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
    volumes:
      - ./db-data:/var/lib/mysql:rw

  webserver:
    build:
      context: docker-config/webserver
      dockerfile: Dockerfile
    image: myapp/webserver
    container_name: webserver
    ports:
      - "80:80"
    volumes:
       - ./src:/www/application.local
       - ./run:/var/run/
       - ./logs:/var/log/nginx
    networks:
      - app-network

  php:
    build:
      context: docker-config/php
      dockerfile: Dockerfile
    image: myapp/php
    container_name: php
    volumes:
       - ./src:/www/application.local
       - ./run:/var/run/
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    networks:
      - app-network

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '11211:11211'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge