CREATE TABLE "movies"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar
);

CREATE TABLE "attribute_types"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" varchar
);

CREATE TABLE "movie_attributes"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "movie"          int,
    "attribute_type" int
);

CREATE TABLE "attribute_type_value"
(
    "id"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "movie_attribute"     int,
    "text"     varchar,
    "decimal"  decimal,
    "int"      int4,
    "date"     date
);

ALTER TABLE "movie_attributes"
    ADD FOREIGN KEY ("movie") REFERENCES "movies" ("id");

ALTER TABLE "movie_attributes"
    ADD FOREIGN KEY ("attribute_type") REFERENCES "attribute_types" ("id");

ALTER TABLE "attribute_type_value"
    ADD FOREIGN KEY ("movie_attribute") REFERENCES "movie_attributes" ("id");

CREATE INDEX movies_name
    ON movies(name);