swagger: "2.0"
info:
  description: "Process API"
  version: "1.0.0"
  title: "Process API"
host: "localhost:8083"
basePath: "/"
tags:
  - name: "process"
    description: "Process API"
schemes:
  - "http"
paths:
  /process:
    post:
      tags:
        - "process"
      summary: "Create a process"
      description: ""
      operationId: "createProcess"
      consumes:
        - "application/xml"
      produces:
        - "application/json"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Process"
  /process/{id}:
    get:
      tags:
        - "process"
      summary: "Get process status by id"
      description: ""
      operationId: "getProcessStatus"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of process"
          required: true
          type: "string"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Process"

definitions:
  Process:
    type: "object"
    properties:
      processId:
        type: "string"
        example: "process640de45ce3be97.00000000"
      status:
        type: "string"
        description: "Process Status"
        enum:
          - "created"
          - "processing"
          - "finished"
          - "not_found"