# Otus PHP Pro course / Lesson 1: docker web-server container sample

version: '3'
services:
    web:
        image: nginx:latest
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "8081:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
            - mysql
    php:
        image: mishaikon/php71:latest
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        ports:
            - "9090:9000"
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    memcached:
        image: memcached:${MEMCACHED_VERSION}
        container_name: ${MEMCACHED_HOST}
        ports:
            - 11212:11211

    redis:
        image: redis:3.2
        volumes:
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
        mem_limit: 100m
        ports:
            - "6379:6379"
        environment:
            TZ : "Europe/Moscow"