parameters:

services:

listeners:
  Cookapp\Php\Infrastructure\EventListener\PreCookEventListener:
    event: Cookapp\Php\Infrastructure\Event\PreCookEvent
  Cookapp\Php\Infrastructure\EventListener\PostCookEventListener:
    event: Cookapp\Php\Infrastructure\Event\PostCookEvent
