version: "3.8"

services:
  app:
    container_name: app
    build: ./fpm
    volumes:
      - ./public:/var/www
    networks:
      - app-net

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - ${APP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public:/var/www
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
