<?php

/**
 * API простых чисел
 * Это учебное API в рамках домашнего задания Otus. Сервис берет целое число и осуществляет проверку на простоту. Задание ставится в очередь и результат доступен по ИД задания. Так как задание учебное по теме API, то здесь вы не встретитие изощренных алгоритмов проверки на простоту.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pashilyaev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The Lumen framework is open-sourced software licensed under the [MIT license](https://opensource.org/licenses/MIT).
 */

/**
 * API простых чисел
 * @version 1.0.0
 */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

$router->get('/', function () { return view('index');});

/**
 * post checkNumber
 * Summary: Добавление числа на проверку
 * Notes: Добавляется задание на проверку, является ли число простым или нет. Каждому запросу присваивается определенный идентификатор, по которому в последсвтие можно узнать результат
 */
$router->post('/v1/number', 'NumberApi@checkNumber');

/**
 * get getResult
 * Summary: Получение результата проверки
 * Notes: Получает результат ранее переданного запроса на проверку простоты числа
 */
$router->get('/v1/task/{taskId}', 'ResultApi@getResult');

