GET http://application.local/test

###
POST http://application.local/channel/create
Content-Type: application/json

{"id":"channel1","name": "name_channel1","description": "description1","subscribers": 1000}

###
GET http://application.local/channel/get?index=channel&id=channel1

###
GET http://application.local/channel/delete?index=channel&id=channel1

###
POST http://application.local/video/create
Content-Type: application/json

{"id":"video2","name": "name_video2","description": "description2","time": "03:00", "channelId": "channel1"}

###
GET http://application.local/video/get?index=video&id=video2

###
GET http://application.local/video/delete?index=video&id=video1