version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: 'otus'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'root'
    ports:
      - "5432:5432"
    volumes:
      - ./../dbdata:/var/lib/postgresql/data/
      - ./../:/var/src/
#    networks:
#      - app-network
