version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: docker-compose/Dockerfile
    image: homebee
    container_name: homebee-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - homebee

  workspace:
    image: php:7.4
    container_name: homebee-console
    volumes:
      - ./:/var/www
    networks:
      - homebee

  db:
    image: mysql:5.7.31
    container_name: homebee-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/.dev/mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - homebee

  memcached:
    container_name: homebee-memcached
    image: memcached:latest
    restart: unless-stopped
    depends_on:
      - db
      - app
    networks:
      - homebee

  redis:
    image: redis:4.0
    container_name: homebee-redis
    restart: unless-stopped
    depends_on:
      - db
      - app
    networks:
      - homebee

  nginx:
    image: nginx:alpine
    container_name: homebee-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - db
      - app
    networks:
      - homebee

networks:
  homebee:
    driver: bridge
