version: '3.8'
services:

  nginx:
    build:
      context: .docker
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "80:80"
    depends_on:
      - php

  php-fpm:
    build:
      context: .docker
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./src:/app

  composer:
    image: composer
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint:
      - composer
      - install
    depends_on:
      - php-fpm

  db-postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-postgres: