# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP-FPM
  app:
    # build'им по готовому докфайлу
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php8 # имя будущего образа
    container_name: app # имя контейнера после запуска
    volumes:
       - ./code:/data/
       - unixsockets:/var/run
volumes:
    unixsockets:
