<?php


namespace App\Controller\Admin;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class BaseController extends AbstractController
{
    protected function render(string $view, array $parameters = [], Response $response = null): Response
    {
        $parameters['roles'] = json_encode($this->getUser()->getRoles());
        return parent::render( $view, $parameters, $response ); // TODO: Change the autogenerated stub
    }

}