###
POST http://application.local/api/v1/user
Content-Type: application/json

{
  "name": "Pavel",
  "surname": "Gaponenko",
  "email": "test@gmail.com"
}

###
GET http://application.local/api/v1/getUser/4

###
GET http://application.local/api/v1/getUsers

###
GET http://application.local/api/v1/result/22