version: '3'
services:
  php_fpm:
    build: ./images/php_fpm
    restart: always
    volumes:
      - ./www:/var/www
      - ./logs/php:/var/log
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.11.2
    container_name: es
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
  kibana:
    image: kibana:8.5.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch
    restart: "unless-stopped"
networks:
  app-network:
    driver: bridge