old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer

    producers:
        add_scores:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_scores', type: direct}
        send_mail:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.send_mail', type: direct }
        generate_data:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.generate_data', type: direct }


    consumers:
        add_scores:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_scores', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.add_scores'}
            callback: App\Consumer\AddScores\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
        send_mail:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.send_mail', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.send_mail' }
            callback: App\Consumer\SendMail\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }

        generate_data:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.generate_data', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.generate_data' }
            callback: App\Consumer\GenerateData\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }