<?php

/**
 * API простых чисел
 * Это учебное API в рамках домашнего задания Otus. Сервис берет целое число и осуществляет проверку на простоту. Задание ставится в очередь и результат доступен по ИД задания. Так как задание учебное по теме API, то здесь вы не встретитие изощренных алгоритмов проверки на простоту.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pashilyaev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Support\Facades\Request;

class ResultApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation getResult
     *
     * Получение результата проверки.
     *
     * @param string $task_id ИД операции для проверки (required)
     *
     * @return Http response
     */
    public function getResult($taskId)
    {
        if (strlen($taskId)>0)
        {
            //$task = Task::where('uuid', '=',$taskId)->get();

            /** @var Task $task */
            $task = Task::where('uuid', $taskId)->first();
            if (!empty($task)) {
               if ($task->result===null)
                   return response(json_encode(["status"=>"calculating", "result"=>null]), 200);
               else
                   return response(json_encode(["status"=>'ready', "result"=>$task->result]), 200);
            }
            else
                return response(json_encode(["status"=>'error', "result"=>null]), 400);

        }
        else
            return response("Wrong input!", 400);



        return response('How about implementing getResult as a get method ?');
    }
}
