CREATE DATABASE mysite CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'admin'@'*' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'*' WITH GRANT OPTION;

GRANT ALL ON mysite.* TO 'admin'@'%' IDENTIFIED BY 'password';

FLUSH PRIVILEGES;