old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer

    producers:
        create_account_statement:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.create_account_statement', type: direct}

    consumers:
        create_account_statement:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.create_account_statement', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.create_account_statement'}
            callback: App\Infrastructure\Consumer\CreateAccountStatement\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}