CREATE TABLE HALL
(
    ID         SERIAL PRIMARY KEY,
    SEAT_COUNT INT          NOT NULL,
    CATEGORY   VARCHAR(255) NOT NULL
);

CREATE TABLE MOVIE
(
    ID       SERIAL PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    DURATION TIME         NOT NULL
);

CREATE TABLE TIME
(
    ID      SERIAL PRIMARY KEY,
    WEEKDAY VARCHAR(255) NOT NULL,
    DAYTIME VARCHAR(255) NOT NULL
);

CREATE TABLE SESSION
(
    ID       SERIAL PRIMARY KEY,
    MOVIE_ID INT  NOT NULL,
    HALL_ID  INT  NOT NULL,
    TIME_ID  INT  NOT NULL,
    DATE     DATE NOT NULL,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID),
    FOREIGN KEY (HALL_ID) REFERENCES HALL (ID),
    FOREIGN KEY (TIME_ID) REFERENCES TIME (ID)
);

CREATE TABLE TICKET
(
    ID         SERIAL PRIMARY KEY,
    PRICE      INT NOT NULL,
    SEAT       INT NOT NULL,
    SESSION_ID INT NOT NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES SESSION (ID)
);

CREATE TABLE VIEWER
(
    ID         SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    TICKET_ID  INT NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKET (ID)
);