INSERT INTO halls (name, created_at, updated_at) VALUES ('Синий зал', DEFAULT, null);
INSERT INTO halls (name, created_at, updated_at) VALUES ('Красный зал', DEFAULT, null);

INSERT INTO movies (name, duration, created_at, updated_at) VALUES ('Аватар: Путь воды (2022)', 192, DEFAULT, null);
INSERT INTO movies (name, duration, created_at, updated_at) VALUES ('Чебурашка', 113, DEFAULT, null);
INSERT INTO movies (name, duration, created_at, updated_at) VALUES ('Иван Царевич и Серый волк 5', 84, DEFAULT, null);
INSERT INTO movies (name, duration, created_at, updated_at) VALUES ('Ёлки 9', 90, DEFAULT, null);

INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (1, 1, 450, '2023-01-09 15:00:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (1, 1, 450, '2023-01-09 18:35:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (1, 1, 450, '2023-01-09 22:10:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (2, 3, 300, '2023-01-09 11:45:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (2, 3, 350, '2023-01-09 13:30:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (2, 3, 390, '2023-01-09 15:15:00', DEFAULT, null);
INSERT INTO hall_shows (hall_id, movie_id, price, start_date, created_at, updated_at) VALUES (2, 4, 390, '2023-01-09 23:10:00', DEFAULT, null);

INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 1, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 1, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 1, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 2, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 2, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 2, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 3, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 3, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 3, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (1, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 1, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 1, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 1, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 2, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 2, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 3, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 3, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 3, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (2, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 1, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 1, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 1, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 2, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 2, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 2, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 3, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 3, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 3, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (3, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 1, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 1, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 1, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 2, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 2, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 2, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 3, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 3, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 3, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (4, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 1, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 1, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 1, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 1, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 2, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 2, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 2, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 2, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 3, 11, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 3, 12, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 3, 13, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 3, 14, DEFAULT, null);
INSERT INTO tickets (hall_show_id, line, number, created_at, updated_at) VALUES (5, 4, 12, DEFAULT, null);