INSERT INTO `halls` (`name`) VALUES ('Синий зал');
INSERT INTO `halls` (`name`) VALUES ('Красный зал');

INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 1);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 2);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 3);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 4);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 5);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 6);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 7);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 8);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 1, 9);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 1);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 2);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 3);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 4);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 5);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 6);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 7);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 8);
INSERT INTO `halls_places` (`hall_id`, `line`, `number`) VALUES (1, 2, 9);

INSERT INTO `movies` (`name`, `duration`) VALUES ('Аватар: Путь воды (2022)', 192);
INSERT INTO `movies` (`name`, `duration`) VALUES ('Чебурашка', 113);
INSERT INTO `movies` (`name`, `duration`) VALUES ('Иван Царевич и Серый волк 5', 84);
INSERT INTO `movies` (`name`, `duration`) VALUES ('Ёлки 9', 90);

INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (1, 1, 450, '2023-01-09 15:00:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (1, 1, 450, '2023-01-09 18:35:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (1, 1, 450, '2023-01-09 22:10:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (2, 3, 300, '2023-01-09 11:45:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (2, 3, 350, '2023-01-09 13:30:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (2, 3, 390, '2023-01-09 15:15:00');
INSERT INTO `movies_shows` (`hall_id`, `movie_id`, `price`, `start_date`) VALUES (2, 4, 390, '2023-01-09 23:10:00');

INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 2);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 3);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 6);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (1, 9);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 2);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 3);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 6);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 7);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (2, 9);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 3);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 6);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 7);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (3, 9);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 2);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 3);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 6);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 7);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (4, 9);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 2);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 6);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 7);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (5, 9);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 1);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 2);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 4);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 5);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 7);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 8);
INSERT INTO `tickets` (`hall_show_id`, `hall_place_id`) VALUES (6, 9);